### ISSUE TITLE
ts-node

### ISSUE THREAD

**Issue by jersonjunior** [BitcoinCompany/PancakeswapPredictionBot-2023#1]
**Error:**

npm run start -- --with

> pancakeswap@1.0.0 start
> ts-node src/bot.ts "--with"

sh: 1: ts-node: not found

**After installing ts-node:**

npm run start -- --with

> pancakeswap@1.0.0 start
> ts-node src/bot.ts "--with"

/home/myuser/PancakeswapPredictionBot-2023/node_modules/@ethersproject/bytes/src.ts/index.ts:55
    return !!(value.toHexString);
                    ^
TypeError: Cannot read property 'toHexString' of undefined

**Comment by BitcoinCompany** [comment]
try this https://github.com/BitcoinCompany/PancakeswapPredictionBot-2022

**Comment by jersonjunior** [comment]
With https://github.com/BitcoinCompany/PancakeswapPredictionBot-2022 works fine.

There is a problem with 2023 version even installing ts-node
