### ISSUE TITLE
Infinity waiting for new round

### ISSUE THREAD

**Issue by nacimgoura** [BitcoinCompany/PancakeswapPredictionBot-2023#2]
Hello,
I wanted test this tool but always nothing after 1h

![Screenshot from 2023-03-02 16-38-42](https://user-images.githubusercontent.com/9990521/222475896-54c58e2d-9b73-4408-a3c6-f05c76789bf2.png)

**Comment by BitcoinCompany** [comment]
thanks for the feedback I'll check and let you know.

**Comment by BitcoinCompany** [comment]
Update new code.
